language: android
dist: trusty

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - build-tools-29.0.2
    - extra-google-m2repository
    - extra-android-m2repository
    - android-29

jdk:
  - openjdk15
